### ISSUE TITLE
UnboundLocalError: local variable 'retcode' referenced before assignment

### ISSUE THREAD

**Issue by tiansiyuan** [azizk/dil#12]
scripts/build.py
dmd -release -O -odobj -op -version=D2 (94 source files...) -ofbin/dil
Error: command not found: 'dmd'
Traceback (most recent call last):
  File "scripts/build.py", line 203, in <module>
    main()
  File "scripts/build.py", line 197, in main
    retcode = build_func(cmdclass=command, *_cargs)
  File "scripts/build.py", line 137, in build_dil_release
    return build_dil(dict(kwargs, *_options))
  File "scripts/build.py", line 131, in build_dil
    return retcode
UnboundLocalError: local variable 'retcode' referenced before assignment

**Comment by azizk** [comment]
Hi!
Surprised that someone is checking out this dormant project.
The issue was easy to fix. Please try again.
